version: '2.1'

services:
  uplaod-file:
    image: uplaod-file:latest
    environment:
      - BUCKET_NAME=
      - FILE_OBJECT_NAME=
      - FLASK_APP_URL=
      - PROFILE=default
    ports:
      - 8080:8080
